name: cube_transition
description: A 3D Cube transition for PageView and PageRoute
version: 1.0.0

homepage: https://aeyrium.com/
repository: https://github.com/aeyrium/cube_transition

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter: