name: Package Publish dry-run

on:
  push:
    branches: [ dev ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dry-run
        uses: ilteoood/actions-flutter-pub-publisher:master
        with:
          credential: ${{secrets.CREDENTIAL_JSON}}
          flutter_package: false
          skip_test: true
          dry_run: true
