name: Package Publish dry-run

on:
  push:
    branches: [ dev ]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: '>> Dart package Dry-run<<'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          dryRunOnly: true
          skipTests: true
